# .github/FUNDING.yml

# Sponsor Github
# github: Isilin
# Ou alternatives possibles (facultatif)
ko_fi: isilin
# buy_me_a_coffee: your-buymeacoffee-username
# patreon: your-patreon-username
# custom: ["https://buymeacoffee.com/your-page"]
