name: Check & Deploy

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  setup:
    name: Setup the library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache node_modules
        id: cache_nodemodules
        uses: actions/cache@v4
        with:
          key: dependencies
          path: |
            node_modules/**/*
            .prettierignore
            .prettierrc
            package.json
            yarn.lock
            eslint.config.js
            tsconfig.json
            tsup.config.ts
            vite.config.mts
            src/
            .storybook/

      - name: Install dependencies
        if: steps.cache_nodemodules.outputs.cache-hit != 'true'
        run: npm install --include=dev
  lint-and-check:
    name: Lint & type check
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      checks: write
      pull-requests: read
    steps:
      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          key: dependencies
          path: |
            node_modules/**/*
            .prettierignore
            .prettierrc
            package.json
            yarn.lock
            eslint.config.js
            tsconfig.json
            tsup.config.ts
            vite.config.mts
            src/
            .storybook/

      - name: Run ESLint
        run: npm run lint:ci
        continue-on-error: true

      - name: Type checking
        run: npm run typecheck:ci
        continue-on-error: true

      - name: Annotate
        uses: DerLev/eslint-annotations@v2
        with:
          eslint-report: eslint_report.json
          typescript-log: typescript.log
          github-token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Deploy the storybook
    runs-on: ubuntu-latest
    needs: [setup, lint-and-check]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          key: dependencies
          path: |
            node_modules/**/*
            .prettierignore
            .prettierrc
            package.json
            yarn.lock
            eslint.config.js
            tsconfig.json
            tsup.config.ts
            vite.config.mts
            src/
            .storybook/

      - name: Build Storybook
        run: npm run storybook:build

      - name: Configure git user
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Deploy to GitHub Pages
        run: |
          npx gh-pages -d storybook-static -u "github-actions <github-actions@github.com>" -r "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
